### ISSUE TITLE
Show only the final result

### ISSUE THREAD

**Issue by abelrgr** [behdadahmadi/jscrypt#1]
Hi, thanks for your effort in this lib :)

It's possible to have the final result instead the progress?

**Comment by behdadahmadi** [comment]
Hi, thank you for your attention to this lib :)
When progress callback returns `100`,it means that job has been done successfully. I'm sorry,What do you mean by final result?
I'm so sorry that I saw your comment late.

**Comment by abelrgr** [comment]
Instead of use the progress (or a second callback), have the option to have an answer from the callback when the encryption is finished:
```javascript
jscrypto.encryptFile("A.txt","A-encrypted.txt","aes256","P@sW0rD",655000,null, (isDone) =>{
  \\Run a code when the file are encypted
});
```

**Comment by behdadahmadi** [comment]
Thank you. I will update the lib with this new functionality today.

**Comment by behdadahmadi** [comment]
Lib has beed updated.
